export const ADD_TODOS = 'ADD_TODOS';
export const TOGGLE_TODOS = 'TOGGLE_TODOS';
export const DELETE_TODOS = 'DELETE_TODOS';
export const MAKE_ALL_COMPLETED_TODOS = 'MAKE_ALL_COMPLETED_TODOS';
export const DELETE_ALL_COMPLETED_TODOS = 'DELETE_ALL_COMPLETED_TODOS';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';